"use strict";(self.webpackChunkzio_site=self.webpackChunkzio_site||[]).push([[12764],{66835:(e,r,t)=>{t.r(r),t.d(r,{assets:()=>c,contentTitle:()=>a,default:()=>d,frontMatter:()=>i,metadata:()=>n,toc:()=>l});const n=JSON.parse('{"id":"reference/error-management/types/index","title":"Three Types of Errors","description":"We should consider three types of errors when writing ZIO applications:","source":"@site/docs/reference/error-management/types/index.md","sourceDirName":"reference/error-management/types","slug":"/reference/error-management/types/","permalink":"/reference/error-management/types/","draft":false,"unlisted":false,"editUrl":"https://github.com/zio/zio/edit/series/2.x/docs/reference/error-management/types/index.md","tags":[],"version":"current","frontMatter":{"id":"index","title":"Three Types of Errors"},"sidebar":"reference-sidebar","previous":{"title":"Introduction to Error Management in ZIO","permalink":"/reference/error-management/"},"next":{"title":"Failures","permalink":"/reference/error-management/types/failures"}}');var s=t(74848),o=t(28453);const i={id:"index",title:"Three Types of Errors"},a=void 0,c={},l=[];function h(e){const r={a:"a",code:"code",li:"li",ol:"ol",p:"p",strong:"strong",ul:"ul",...(0,o.R)(),...e.components};return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsx)(r.p,{children:"We should consider three types of errors when writing ZIO applications:"}),"\n",(0,s.jsxs)(r.ol,{children:["\n",(0,s.jsxs)(r.li,{children:["\n",(0,s.jsxs)(r.p,{children:[(0,s.jsx)(r.strong,{children:(0,s.jsx)(r.a,{href:"/reference/error-management/types/failures",children:"Failures"})})," are expected errors. We use ",(0,s.jsx)(r.code,{children:"ZIO.fail"})," to model failures. As they are expected, we know how to handle them. We should handle these errors and prevent them from propagating throughout the call stack."]}),"\n"]}),"\n",(0,s.jsxs)(r.li,{children:["\n",(0,s.jsxs)(r.p,{children:[(0,s.jsx)(r.strong,{children:(0,s.jsx)(r.a,{href:"/reference/error-management/types/defects",children:"Defects"})})," are unexpected errors. We use ",(0,s.jsx)(r.code,{children:"ZIO.die"})," to model a defect. As they are not expected, we need to propagate them through the application stack, until in the upper layers one of the following situations happens:"]}),"\n",(0,s.jsxs)(r.ul,{children:["\n",(0,s.jsx)(r.li,{children:"In one of the upper layers, it makes sense to expect these errors. So we will convert them to failure, and then they can be handled."}),"\n",(0,s.jsx)(r.li,{children:"None of the upper layers will catch these errors, so it will finally crash the whole application."}),"\n"]}),"\n"]}),"\n",(0,s.jsxs)(r.li,{children:["\n",(0,s.jsxs)(r.p,{children:[(0,s.jsx)(r.strong,{children:(0,s.jsx)(r.a,{href:"/reference/error-management/types/fatals",children:"Fatals"})})," are catastrophic unexpected errors. When they occur we should kill the application immediately without propagating the error furthermore. At most, we might need to log the error and print its call stack."]}),"\n"]}),"\n"]})]})}function d(e={}){const{wrapper:r}={...(0,o.R)(),...e.components};return r?(0,s.jsx)(r,{...e,children:(0,s.jsx)(h,{...e})}):h(e)}},28453:(e,r,t)=>{t.d(r,{R:()=>i,x:()=>a});var n=t(96540);const s={},o=n.createContext(s);function i(e){const r=n.useContext(o);return n.useMemo((function(){return"function"==typeof e?e(r):{...r,...e}}),[r,e])}function a(e){let r;return r=e.disableParentContext?"function"==typeof e.components?e.components(s):e.components||s:i(e.components),n.createElement(o.Provider,{value:r},e.children)}}}]);